[project]
name = "music-lyric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audio-separator[cpu]>=0.39.0",
    "beautifulsoup4>=4.14.2",
    "ddgs>=9.6.0",
    "duckduckgo-search>=8.1.1",
    "faster-whisper>=1.2.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.30",
    "langchain-openai>=0.1.0",
    "mutagen>=1.47.0",
    "openai>=2.0.1",
    "pydantic>=2.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
